//LOCALHOST 
    GET http://localhost:8080/bikes
    GET http://localhost:8080/contacts/63b9bce9586401e1360b7da2
    GET http://localhost:8080/contacts/63b9bda8586401e1360b7da4
    GET http://localhost:8080/contacts/63b9bdef586401e1360b7da5
    POST http://localhost:8080/contacts HTTP/1.1
        {"firstName":"Carissa","lastName":"Marshall","email":"dragonseye@hotmail.com","birthday":"3/13/2000","favColor":"Red"}
    PUT http://localhost:8080/bikes.js/63cc349755c793a75d6b7fcf HTTP/1.1
        {"firstName":"Brenda","lastName":"Measom","email":"tsarinalea@gmail.com","birthday":"8/4/2000","favColor":"Pink"}
    DELETE http://localhost:8080/bikes.js/63cc349755c793a75d6b7fcf HTTP/1.1

//PRODUCTION
    GET https://cse341-l3-bc0t.onrender.com/contacts
    GET https://cse341-l3-bc0t.onrender.com/contacts/63b9bce9586401e1360b7da2
    GET https://cse341-l3-bc0t.onrender.com/contacts/63b9bda8586401e1360b7da4
    GET https://cse341-l3-bc0t.onrender.com/contacts/63b9bdef586401e1360b7da5
    POST https://cse341-l3-bc0t.onrender.com/contacts HTTP/1.1
        {"firstName":"Carissa","lastName":"Marshall","email":"dragonseye@hotmail.com","birthday":"3/13/2000","favColor":"Red"}
    PUT https://cse341-l3-bc0t.onrender.com/contacts63cc349755c793a75d6b7fcf HTTP/1.1
        {"firstName":"Brenda","lastName":"Measom","email":"tsarinalea@gmail.com","birthday":"8/4/2000","favColor":"Pink"}
    DELETE https://cse341-l3-bc0t.onrender.com/contacts63cc349755c793a75d6b7fcf HTTP/1.1
