//LOCALHOST 
    GET http://localhost:8080/bikes
    GET http://localhost:8080/bikes/63d9f51ca383e9d058e12311
    GET http://localhost:8080/bikes/63d9f579a383e9d058e12312
    POST http://localhost:8080/bikes HTTP/1.1
        {"make":"Kawasaki","model":"KLR650","year":"2009","motor":"4-stroke, single","displacement":"651cc","transmission":"5-speed","drive":"Chain","terrain":"Dual Sport"}
    PUT http://localhost:8080/bikes.js/63d9f51ca383e9d058e12311 HTTP/1.1
        {"make":"Harley-Davidson","model":"Road Glide","year":"2020","motor":"V-twin","displacement":"107ci","transmission":"6-speed","drive":"Belt","terrain":"Street"}
    DELETE http://localhost:8080/bikes.js/63d9f579a383e9d058e12312

//PRODUCTION
    GET http://localhost:8080/bikes
    GET http://localhost:8080/bikes/63d9f51ca383e9d058e12311
    GET http://localhost:8080/bikes/63d9f579a383e9d058e12312
    POST http://localhost:8080/bikes HTTP/1.1
        {"make":"Kawasaki","model":"KLR650","year":"2009","motor":"4-stroke, single","displacement":"651cc","transmission":"5-speed","drive":"Chain","terrain":"Dual Sport"}
    PUT http://localhost:8080/bikes.js/63d9f51ca383e9d058e12311 HTTP/1.1
        {"make":"Harley-Davidson","model":"Road Glide","year":"2020","motor":"V-twin","displacement":"107ci","transmission":"6-speed","drive":"Belt","terrain":"Street"}
    DELETE http://localhost:8080/bikes.js/63d9f579a383e9d058e12312
